# Generated by Django 3.0.7 on 2020-07-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_auto_20200709_2118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Productos',
        ),
    ]
