# Generated by Django 3.0.7 on 2020-07-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0009_auto_20200720_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
